spring:
  profiles:
    active: @activatedProperties@
---
spring:
  profiles:
    dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/racing?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
parsing:
  loggingEnabled: true
  createSnapshots: true
---
spring:
  profiles:
    release
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:4000/racing?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
parsing:
    loggingEnabled: false
    createSnapshots: false